version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped

  # client:
  #   build: ./frontend
  #   container_name: web-demo
  #   ports:
  #     - "8080:80"
  #   env_file:
  #     - ./frontend/.env

  # restful-server:
  #   build: ./restful-notification
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - ./restful-notification/.env

  # sse-server:
  #   build: ./sse-notification
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./sse-notification/.env

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
